apiVersion: v1
kind: Service
metadata:
  name: weather-api
  namespace: uav-platform
  labels:
    app.kubernetes.io/name: weather-api
    app.kubernetes.io/part-of: uav-platform
    app.kubernetes.io/component: microservice
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: weather-api
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
